<?php 



/**
 * Implements hook_permission().
 */

function cornerstone_toolsbar_permission() {
  return array(
    'access cornerstone toolsbar' => array(
      'title' => t('cornerstone module permission'),
      'description' => t('cornerstone module permission'),
      'restrict access' => TRUE,
  ));
}


function cornerstone_toolsbar_page_build(&$page) {
	// dpm($page);
	if (user_access('access cornerstone toolsbar')) {
	$module_path = drupal_get_path('module', 'cornerstone_toolsbar');

		drupal_add_css($module_path.'/css/cornerstone.navtools.css',
		[
			'gorup' => CSS_THEME,
			'media' => 'all',
			'weight'=> 1002
		]);
		drupal_add_css($module_path.'/css/cornerstone.font.css',
		[
			'gorup' => CSS_THEME,
			'media' => 'all',
			'weight'=> 1003
		]);
		drupal_add_js($module_path.'/js/cornerstone.navtools.js');

	}
}

function cornerstone_toolsbar_page_alter(&$page) {

	if  (user_access('access cornerstone toolsbar')) {
		$main_menu_tree = menu_tree(variable_get('menu_navtools', 'menu-navtools')); 
		$navtools = drupal_render($main_menu_tree);
		//$navtools = '<div id="navtools">' . $navtools . '</div>';

	global $user;
	
	if (in_array('administrator', $user->roles)) {
		$adminif = 'class="isadmin"';
	}else{
		$adminif = '';
	}

		$output = '';
		$output .= '<div id="cornerstone-tools" ' . $adminif . '>';
		$output .= '  <div class="profile-menu">';
		$output .= '    <a href="">';
		$output .= '      <div class="profile-pic"></div>';
		$output .= '      <div class="profile-info"> ' .  $user->name . '<i class="caret"></i></div>';
		$output .= '    </a>';
		$output .= '  <ul id="profile-info" class="menu nav" >';
		// $output .= '	  <li>'.l(t('View Profile'), "user/".$user->uid, array('attributes' => array('class' => 'icon-profile'))).'</li>';
		// $output .= '	  <li>'.l(t('Settings'), "user/".$user->uid."/edit", array('attributes' => array('class' => 'icon-cog'))).'</li>';
		// $output .= '	  <li>'.l(t('Log out'), 'user/logout', array('attributes' => array('class' => 'icon-exit'))).'</li>';
		$output .= '    <li><a href="/user/' .  $user->uid . '"><i class="icon-profile"></i> ' . t('View Profile') . '</a></li>';
		$output .= '    <li><a href="/user/' .  $user->uid . '/edit"><i class="icon-cog"></i> ' . t('Settings') . '</a></li>';
		$output .= '    <li><a href="/user/logout"><i class="icon-exit"></i> ' . t('Log out') . '</a></li>';
		$output .= '  </ul>';
		$output .= '     </div>';
		$output .=  '<div id="navtools">' . $navtools . '</div>';
		if  (user_access('Administer permissions')){
			$output .=  '<div id="navtools-setup"><a href="/admin/structure/menu/manage/menu-navtools" ><i class="icon-cogs icon-big"></i></a><a target="_blank" href="/sites/all/modules/custom/cornerstone_toolsbar/font.html" ><i class="icon-plus icon-big"></i></a></div>';
		}
		$output .= '</div>';

		//print $output;
		$page['page_bottom']['cornerstone_toolsbar'] = array(
		  '#weight' => -10,
		  '#markup' => $output,
		);
	}
}
